### PR TITLE
Adds github stars on navigation menu

### PR DESCRIPTION
**Pull request by 1995parham**
Since this repository has many stars let's show them on navigation menu :joy:

### CODE REVIEW

**Comment by 1995parham** [comment]
@pesehr what do you think ?

**Comment by pesehr** [comment]
@sajjadrahnama7  plz merge it

**Comment by 1995parham** [comment]
🙈 🙈 Thanks ! @pesehr @sajjadrahnama7

**Comment by sajjadrahnama** [comment]
I fixed the position of stars button.
script must be placed at app.blade.php  👍

**Comment by 1995parham** [comment]
Thanks, sorry for my mistake 😭

**Pull request merged**
